// Build helper (no dependencies).
//   node build.js                      -> rebuild standalone.html (index.html with all scripts inlined)
//   node build.js --icons <lucide-dir> -> also regenerate icons.js from a lucide-static icons folder
//                                         (get one with: npm pack lucide-static && tar xzf lucide-static-*.tgz
//                                          then pass package/icons). Only icon names used in index.html are kept.
const fs = require('fs');
const path = require('path');
const here = f => path.join(__dirname, f);
const html = fs.readFileSync(here('index.html'), 'utf8');

const i = process.argv.indexOf('--icons');
if (i > -1) {
  const dir = process.argv[i + 1];
  const names = [...new Set([...html.matchAll(/['"]([a-z][a-z0-9-]*)['"]/g)].map(m => m[1]))]
    .filter(n => fs.existsSync(path.join(dir, n + '.svg'))).sort();
  const icons = {};
  for (const n of names) {
    const svg = fs.readFileSync(path.join(dir, n + '.svg'), 'utf8');
    icons[n] = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>')).replace(/\s*\n\s*/g, '');
  }
  fs.writeFileSync(here('icons.js'),
    '// Lucide icons (ISC licence, lucide.dev), inlined so the site works offline. Generated by build.js.\n' +
    'const ICONS = ' + JSON.stringify(icons, null, 0).replace(/","/g, '",\n"') + ';\n');
  console.log('icons.js:', names.length, 'icons');
}

const inlined = html.replace(/<script src="([^"]+)"><\/script>/g, (_, src) =>
  '<script>\n' + fs.readFileSync(here(src), 'utf8').replace(/<\/script>/gi, '<\\/script>') + '\n</script>');
fs.writeFileSync(here('standalone.html'), inlined);
console.log('standalone.html:', (inlined.length / 1024).toFixed(0), 'KB');
