"""Builds the latent-semantic (LSA) index used by both engines.
   python backend/scripts/build_semantic.py   (after node backend/scripts/export_data.js)
Each standard becomes a document = title + scope + category, augmented with the
English synonym set and the Hindi/Marathi words that map to its concepts, so that
terms that never co-occur in a keyword sense (e.g. 'geyser' / 'storage water
heater' / 'गीजर') land close together in a low-dimensional concept space.
Query time: sum the (idf-weighted) term vectors of the query -> cosine vs each standard."""
import json, re, math, pathlib
import numpy as np
from sklearn.decomposition import TruncatedSVD
root = pathlib.Path(__file__).resolve().parents[2]
std = json.load(open(root/'backend/data/standards.json'))
lex = json.load(open(root/'backend/data/lexicon.json'))
STOP = set(lex['stopwords']); SYN = lex['synonyms']; DEVA = lex['devanagari']
def tok(t): return [w for w in re.sub(r'[^a-z0-9\u0900-\u097F\s./-]',' ',t.lower()).split() if len(w)>1 and w not in STOP]
rev = {}
for h,e in DEVA.items(): rev.setdefault(e,[]).append(h)
def expand(tokens):
    out = list(tokens)
    for t in tokens:
        for key,syns in SYN.items():
            if t==key or t in syns:
                out += [key]+[w for s in syns for w in s.split()]
                out += rev.get(key,[])
        out += rev.get(t,[])
    return out
docs = []
for s in std:
    base = tok(s['title']+' '+s['scope']+' '+s['cat'])
    docs.append(base + expand(base))
vocab = sorted({w for d in docs for w in d})
ix = {w:i for i,w in enumerate(vocab)}
N = len(docs)
df = np.zeros(len(vocab))
X = np.zeros((N,len(vocab)))
for i,d in enumerate(docs):
    for w in d: X[i,ix[w]] += 1
df = (X>0).sum(0)
idf = np.log((N+1)/(df+1))+1
X = np.log1p(X)*idf
X /= np.linalg.norm(X,axis=1,keepdims=True)+1e-9
K = 48
svd = TruncatedSVD(n_components=K, random_state=7).fit(X)
V = svd.components_.T                     # terms x K
D = X @ V                                  # docs x K
D /= np.linalg.norm(D,axis=1,keepdims=True)+1e-9
T = V * idf[:,None]
out = {'k':K,'terms':{w:[round(float(x),2) for x in T[i]] for w,i in ix.items() if np.linalg.norm(T[i])>0.05},
       'docs':{s['no']:[round(float(x),3) for x in D[i]] for i,s in enumerate(std)}}
json.dump(out, open(root/'backend/data/semantic.json','w'), separators=(',',':'))
open(root/'frontend/semantic-index.js','w').write('// Generated by backend/scripts/build_semantic.py — latent semantic (LSA) index.\nconst SEMANTIC = '+json.dumps(out,separators=(',',':'))+';\n')
print('standards',N,'terms',len(out['terms']),'k',K)
